# Site settings
<<<<<<< HEAD
title: Modern Blog
description: Modern-Blog A Elegant template for Jekyll
keywords: Modern, Blogging, Fun
author: Wferr
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
=======
title: José Vitor
description: José Vitor Portfolio
keywords: professor, Xadrez, R, matemática
author: IMG_FSB
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jvkiler.github.io/#" # the base hostname & protocol for your site
permalink: /:collection/:path/
>>>>>>> f0ffc964e663419ae27301a07c150b17796703c5
